model:
  backbone: resnet18
  num_classes: 44
  top_k_checkoints: 3

train:
  amp: True # set this to True, if your GPU supports FP16. 2080Ti - okay, 1080Ti - not okay
  weights_dir: weights/supcon_second_stage
  stage: second

dataset: data/product_version3

dataloaders:
  train_batch_size: 200 # the higher - the better
  valid_batch_size: 200
  num_workers: 12 # set this to num of threads in your CPU

